### ISSUE TITLE
Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by lukfor85** [verful/adonis-notifications#3]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Description

If this is a feature request, explain why it should be added. Specific use-cases are best.

For bug reports, please provide as much *relevant* info as possible.

## Package version
2.0.2

## Error Message & Stack Trace

err: {
2022-08-02T09:57:23.591840955Z       "type": "SyntaxError",
2022-08-02T09:57:23.591846064Z       "message": "Unexpected token o in JSON at position 1",
2022-08-02T09:57:23.591851234Z       "stack":
2022-08-02T09:57:23.591855993Z           SyntaxError: Unexpected token o in JSON at position 1
2022-08-02T09:57:23.591860772Z               at JSON.parse (<anonymous>)
2022-08-02T09:57:23.591866212Z               at Object.consume (/opt/microservices/node_modules/@verful/notifications/build/src/Models/DatabaseNotification.js:41:38)
2022-08-02T09:57:23.591871723Z               at /opt/microservices/node_modules/@adonisjs/lucid/build/src/Orm/BaseModel/index.js:1196:37
2022-08-02T09:57:23.591876812Z               at Array.forEach (<anonymous>)
2022-08-02T09:57:23.591881732Z               at Proxy.$consumeAdapterResult (/opt/microservices/node_modules/@adonisjs/lucid/build/src/Orm/BaseModel/index.js:1183:40)
2022-08-02T09:57:23.591886851Z               at Function.$createFromAdapterResult (/opt/microservices/node_modules/@adonisjs/lucid/build/src/Orm/BaseModel/index.js:274:18)
2022-08-02T09:57:23.591891921Z               at /opt/microservices/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:197:50
2022-08-02T09:57:23.591896890Z               at Array.reduce (<anonymous>)
2022-08-02T09:57:23.591920064Z               at HasManyQueryBuilder.execQuery (/opt/microservices/node_modules/@adonisjs/lucid/build/src/Orm/QueryBuilder/index.js:195:37)
2022-08-02T09:57:23.591925344Z               at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-02T09:57:23.591930183Z       "status": 500
2022-08-02T09:57:23.591935082Z     }

## Relevant Information
This is happening every time I want to access users' database notifications. I followed the instructions (pretty straightforward to be honest) but didn't come to a working solution. FYI, the database is Postgres.

I identified that this part of the code is responsible for that: 

`@column({
      prepare: (value) => JSON.stringify(value),
      consume: (value) => JSON.parse(value),
    })
    public data: Record<string, any>
`
from src/Models/DatabaseNotification.ts

why is stringifying and parsing necessary? Adonis handles jsons automatically, doesn't it?

**Comment by arthur-er** [comment]
It depends on the db, it handles automatically for pretty much all the ones I tried except SQLite.

Can you provide an example of the data you are trying to store?

**Comment by lukfor85** [comment]
> It depends on the db, it handles automatically for pretty much all the ones I tried except SQLite.
> 
> Can you provide an example of the data you are trying to store?

here it is:
`public toDatabase(_user: User) {
        return {
            type: 'OVERDUE_PAYMENT',
            text: `Reminder by ${this.issuerName}: ${this.note}`,
        };
    }`

- it is stored correctly but when I want to get it, it's not working. I noticed, that Adonis doesn't need prepare & consume for jsons. I am using jsons in other tables in my DB and everything works flawlessly without needing to stringify on input and parse on output.
- That is why I am asking

**Comment by arthur-er** [comment]
I dont looked at the JSON serializing process of lucid, but i think Adonis leaves it to the database driver, and in the case of SQLite, it doesn't handle serialization properly, anyway, i will look for a fix and try to release it tomorrow.

**Comment by steveyout** [comment]
i faced same issue with postgres too

**Comment by justDare** [comment]
Same thing here on postgres, great package though. Commenting out the prepare/consume on the data column fixes the issue.
